# Generated by Django 4.1 on 2022-08-14 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('vendor_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('business_name', models.CharField(max_length=50, null=True, unique=True)),
                ('opening_hours', models.TimeField()),
                ('closing_hours', models.TimeField()),
                ('verified', models.BooleanField(default=False)),
                ('company_banner', models.ImageField(default='default.jpg', null=True, upload_to='profile_pics')),
                ('vendor_profile_completed', models.BooleanField(default=False)),
                ('gas_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('saved_customers', models.ManyToManyField(blank=True, related_name='Saved_Cus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
