# Generated by Django 4.1 on 2022-08-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='company_banner',
            field=models.ImageField(null=True, upload_to='profile_pics/'),
        ),
    ]
