# Generated by Django 4.1 on 2022-08-14 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasOrder',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=100, null=True)),
                ('total_KG', models.IntegerField(default=0)),
                ('date_canceled', models.DateTimeField()),
                ('date_delivered', models.DateTimeField()),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
