# Generated by Django 4.1 on 2022-08-14 17:19

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('username', models.CharField(max_length=50, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='email_address')),
                ('state', models.CharField(max_length=50, null=True)),
                ('lga', models.CharField(max_length=100, null=True)),
                ('phoneNumber', models.CharField(max_length=14, null=True)),
                ('Address', models.CharField(max_length=200, null=True)),
                ('reg_complete', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(default='default.jpg', null=True, upload_to='profile_pics')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('vendor', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-date_joined',),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
